# TerraGalicia MVP Mosquitto configuration
# WARNING: allow_anonymous true is for MVP/development only.

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_type all
